# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345pass
      MYSQL_DATABASE: TaxiProject
      MYSQL_USER: Andrii
      MYSQL_PASSWORD: 111

  adminer:
    image: adminer
    restart: always
    ports:
      - "8095:8080"